# Nom du site
site_name: A bioinformatics website

# Description facultative (utilisée dans les métadonnées et les moteurs de recherche)
site_description: ""

# URL de base (utile pour le déploiement sur GitHub Pages)
site_url: https://srh-bzd.github.io/bioinfo-website

# URL et nom du repo
repo_url: https://github.com/srh-bzd/bioinfo-website
repo_name: srh-bzd/bioinfo-website
edit_uri: edit/main/docs/

# Chemin du logo
# logo: images/logo.png

# Thème Material
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - header.autohide
  palette:
    - scheme: default
      primary: black 
      accent: blue 
      toggle:
        icon: material/lightbulb-night-outline
        name: Mode sombre
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Mode clair
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.code.copy
    - navigation.tabs
    - search.highlight

# Configuration des plugins
plugins:
  - search

# Extensions Markdown
markdown_extensions:
  - tables          
  - toc             
  - codehilite     
  - pymdownx.extra  
  - pymdownx.snippets  

# Structure de la navigation
nav:
  - Accueil: index.md
  - Outils :
    - wgsim : tools/wgsim.md
  - Base de données et références :
    - Bases de données : 
      - RefSeq : databases/refseq.md
      - PaVE : databases/pave.md
    - Références : 
      - Le transcriptome humain : references/human-transcriptome.md
      - Le génome humain: references/human-genome.md
      - Les annotations du génome humain : references/human-annotations.md 
  - Tutoriels :
    - Développement :
      - MkDocs : training/mkdocs.md
    - Visualisation :
      - Diagramme de Venn : training/venn.md
  - Concepts :
      - Inférence du strandedness : concepts/rnaseq-strandedness.md
      - Biais d'assemblage : concepts/assembly-bias.md
  - À propos: about.md


